connection: &connection
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: vagrant
  password: vagrant

development:
  <<: *connection
  database: avion_development

test:
  <<: *connection
  database: avion_test

production:
  <<: *connection
  database: avion_production
